baseURL = ''
languageCode = 'en-us'
title = 'Mike and Tech'
theme = "hugo-coder"

[params]
author = "Michael Helmers"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Mike Helmers's personal website"
keywords = "blog,cybersecurity,personal,helmers,mike,michaelhelmers"
info = ["Brewer", "Cybersecurity", "Dad", "Tinkerer"]
avatarURL = "images/avatar.jpg"
gravatar = "mikehelmers@protonmail.com"
dateFormat = "January 2, 2006"
since = 2015
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/northsaluki615/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 5
  url = "https://twitter.com/mphelmers/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/michaelhelmers/"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-2x fa-mastodon"
  weight = 3
  url = "https://infosec.exchange/@northsaluki615"
  #url = "<a rel="me" href="https://infosec.exchange/@northsaluki615"></a>"
  rel = "me" 
[[params.social]]
  name = "Pixelfed"
  icon = "fa fa-2x fa-pixelfed"
  weight = 4
  url = "https://pixelfed.social/@mhelmers"
  rel = "me" 
[[params.social]]
  name = "RSS"
  icon = "fa fa-2x fa-rss"
  weight = 6
  url = "https://helmers.io/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
